AWSTemplateFormatVersion: 2010-09-09

Description: Service-Workbench-on-AWS ALB for RStudio IDE

Parameters:
  Namespace:
    Type: String
    Description: An environment name that will be prefixed to resource names
  
  VPC:
    Description: The VPC in which the EC2 instance will reside
    Type: AWS::EC2::VPC::Id
    Default: vpc-096b034133955abba
  Subnet1:
    Description: The VPC subnet in which the EC2 instance will reside
    Type: AWS::EC2::Subnet::Id
    Default: subnet-0a661d9f417ecff3f 
  Subnet2:
    Description: The VPC subnet in which the EC2 instance will reside
    Type: AWS::EC2::Subnet::Id
    Default: subnet-0a4cacb60354b8742
  ACMSSLCertARN:
    Type: String
    Description: The ARN of the AWS Certificate Manager SSL Certificate to associate with the Load Balancer
    Default: arn:aws:acm:us-east-1:484479102124:certificate/7028e5b5-be20-4cf2-be41-a71e889abcf9
Resources:
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Ref Namespace
      Scheme: internet-facing # or internal
      Subnets:
      - Ref: Subnet1
      - Ref: Subnet2
      SecurityGroups: 
      - Ref: ALBSecurityGroup
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      SecurityGroupIngress:
        - CidrIp: "0.0.0.0/0"
          FromPort: 22
          ToPort: 22
          IpProtocol: tcp
        - CidrIp: "0.0.0.0/0"
          FromPort: 443
          ToPort: 443
          IpProtocol: tcp
        - CidrIp: "0.0.0.0/0"
          FromPort: 80
          ToPort: 80
          IpProtocol: tcp
      GroupDescription: ALB SecurityGroup
      VpcId: !Ref VPC
Outputs:
  ALBARN:
    Value: !Ref ApplicationLoadBalancer